name: Run Test Suites

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Check out your repository
      - run: npm # Install dependencies
      - run: npm test --coverage # Run test
      - run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
